[package]
name = "CVE-2022-22963-Exploit"
version = "0.1.0"
edition = "2021"
author = "SourMilk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
